version: '3.8'
services:
  mongo:
    image: 'mongo:latest'
    container_name: 'mongo-metal'
    environment: 
      - MONGO_INITDB_DATABASE=universe
    volumes: 
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    ports:
      - '27017-27019:27017-27019'